// Build script for the Pearl Vanity committed browser bundles.
//  1. pearl-vanity-grind.bundle.js — IIFE (PearlVanityGrind) grind core for workers.
//  2. grind-worker.js — grind bundle + classic worker driver (spawn directly, or…)
//  3. src/worker-src.js — GENERATED: grind-worker.js as an exported string.
//  4. pearl-vanity.bundle.js — IIFE (PearlVanity) page bundle; embeds WORKER_SRC
//     so the page spawns workers from a Blob URL (works on https AND file://).
//
// Crypto resolves through ../sign/importmap.json (same plugin as the other apps).
// Usage: node build.mjs   (esbuild resolved via ~/workspace/.build-tools)
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
let esbuild;
try {
  esbuild = require("esbuild");
} catch {
  esbuild = createRequire("/home/hatch/workspace/.build-tools/package.json")("esbuild");
}

const here = dirname(fileURLToPath(import.meta.url));
const signDir = resolvePath(here, "..", "sign");
const map = JSON.parse(readFileSync(resolvePath(signDir, "importmap.json"), "utf8")).imports;
const keys = Object.keys(map).sort((a, b) => b.length - a.length);

const importmapPlugin = {
  name: "importmap",
  setup(build) {
    build.onResolve({ filter: /^[^./]/ }, (args) => {
      for (const k of keys) {
        if (k.endsWith("/") && args.path.startsWith(k)) {
          return { path: resolvePath(signDir, map[k].slice(2) + args.path.slice(k.length)) };
        }
        if (args.path === k) {
          return { path: resolvePath(signDir, map[k].slice(2)) };
        }
      }
      return null;
    });
  },
};

async function bundle(entry, globalName, outfile) {
  await esbuild.build({
    entryPoints: [resolvePath(here, entry)],
    bundle: true,
    format: "iife",
    globalName,
    platform: "browser",
    target: "es2020",
    minify: false,
    outfile: resolvePath(here, outfile),
    plugins: [importmapPlugin],
    logLevel: "warning",
    banner: {
      js: `/* Pearl Vanity bundle (window.${globalName}) — built with esbuild from ${entry}. Do not edit by hand; run \`node build.mjs\`. */`,
    },
  });
  console.log("wrote", outfile);
}

// 1. grind core
await bundle("src/grind-entry.js", "PearlVanityGrind", "pearl-vanity-grind.bundle.js");

// 2. worker script = grind bundle + driver
const grindBundle = readFileSync(resolvePath(here, "pearl-vanity-grind.bundle.js"), "utf8");
const driver = readFileSync(resolvePath(here, "src/worker-driver.js"), "utf8");
const workerSrc =
  "/* Pearl Vanity worker (grind-worker.js) — grind bundle + driver, generated by `node build.mjs`. Do not edit by hand. */\n" +
  grindBundle + "\n" + driver;
writeFileSync(resolvePath(here, "grind-worker.js"), workerSrc);
console.log("wrote grind-worker.js");

// 3. inline worker source for the page bundle
writeFileSync(
  resolvePath(here, "src/worker-src.js"),
  "/* GENERATED by build.mjs — grind-worker.js embedded as a string. Do not edit by hand. */\nexport const WORKER_SRC = " +
    JSON.stringify(workerSrc) + ";\n"
);
console.log("wrote src/worker-src.js");

// 4. page bundle (embeds WORKER_SRC)
await bundle("src/index.js", "PearlVanity", "pearl-vanity.bundle.js");
