/* Pearl Swap core — trustless PRL<->BTC atomic swaps via Taproot HTLCs.
 *
 * Pure ESM, zero build step for developers. The browser ships a committed
 * esbuild IIFE bundle (pearl-swap.bundle.js); node runs this file directly
 * for the verification suite.
 *
 * Protocol (standard hash+timelock atomic swap):
 *   Alice (PRL side, initiator) and Bob (BTC side) agree off-page on:
 *     - PRL amount, BTC amount (coordination only — no BTC moves through Pearl)
 *     - secret hash H = SHA-256(preimage), preimage generated by Alice
 *     - timelocks T1 (Alice's PRL refund, longer) and T2 (Bob's BTC refund
 *       deadline, shorter)
 *   Alice locks PRL in the Pearl HTLC below; Bob mirrors on Bitcoin with the
 *   shorter timeout. Bob claims the PRL by revealing the preimage on Pearl;
 *   Alice extracts the preimage from Bob's claim tx and claims the BTC.
 *   Non-cooperation: Alice refunds PRL after T1; Bob refunds BTC after T2.
 *
 * Pearl-side Taproot contract (two leaves under a NUMS internal key — no
 * keypath backdoor, following the covenant pattern, lifted to the curve from
 * H("PearlSwapNUMS/v1" || claimLeafHash || refundLeafHash)):
 *   claim leaf  (Bob's):  OP_SHA256 <H> OP_EQUALVERIFY <bob_xonly> OP_CHECKSIG
 *     witness = [bob_sig, preimage, claimScript, controlBlock]
 *   refund leaf (Alice's): <T1> OP_CHECKLOCKTIMEVERIFY OP_DROP <alice_xonly> OP_CHECKSIG
 *     refund tx uses nLockTime = T1 and input nSequence = 0xfffffffe
 *     (nSequence 0xffffffff is structurally refused: the builder takes no
 *     sequence parameter and hard-codes 0xfffffffe).
 *
 * Both T1 and T2 are Pearl block heights in the swap spec: T1 is the absolute
 * height in the Pearl refund leaf; T2 is the latest point (expressed as a
 * Pearl height) by which Bob's BTC refund may become valid. The Bitcoin
 * mirror template converts T2 to a Bitcoin height from the parties' agreed
 * Bitcoin tip. The contract requires T1 > T2, and warns when T1 - T2 < 144
 * blocks (~7.8h at Pearl's ~194s/block) — the safety margin guidance.
 *
 * Crypto lineage: key derivation, TapTweak, bech32m, BIP-341 sighash, wire
 * serialization and keypath tx building come from the audited
 * files/pages/sign/src/crypto.js; script-path sighash/spend/fee helpers come
 * from files/pages/escrow/src/escrow-core.js. New here: only the two HTLC
 * script templates, the NUMS derivation, the swap spec/descriptor, the
 * claim/refund/lock spend builders, the segwit tx parser + preimage
 * extractor, and the Bitcoin mirror template. The claim/refund scripts use
 * only opcodes shared by Pearl and Bitcoin script (OP_SHA256, OP_EQUALVERIFY,
 * OP_CHECKSIG, OP_CHECKLOCKTIMEVERIFY, OP_DROP), so the Bitcoin mirror is
 * byte-identical script under a bc1p/tb1p address.
 *
 * Scope (v1): one swap UTXO per claim/refund (single-input spends). The page
 * NEVER builds Bitcoin transactions — the BTC side is assembled by the
 * counterparty's own Bitcoin tooling from the exact exported template.
 */

import {
  taggedHash, tapLeafHash, encodeBech32m, decodeBech32m,
  schnorr, sha256, bytesToHex, hexToBytes, convertBits,
  varint, u32le, u64le, p2trScriptPubKey, txidLE, dblSha,
  DUST_GRAIN, GRAIN_PER_PRL, NETWORKS,
  walletFromMnemonic, walletFromWIF, walletFromPriv, walletToWIF, newMnemonic,
  fetchUtxos, fetchFeeRateGrainsPerVByte, broadcastTx, fetchTxStatus,
  keypathTxVBytes, buildKeypathTx, keypathSigDigestEx, tweakKeypath,
} from "../../sign/src/crypto.js";
import {
  partyKeyFromInput, parseXOnlyKey, scriptPathSigDigestEx,
  signForXOnly, verifySchnorrSig, buildScriptPathSpend,
  spendVBytes, planSpend, addressToProgram,
} from "../../escrow/src/escrow-core.js";
import { secp256k1 } from "@noble/curves/secp256k1";
import { bytesToNumberBE, numberToBytesBE } from "@noble/curves/abstract/utils";

export {
  DUST_GRAIN, GRAIN_PER_PRL, NETWORKS,
  walletFromMnemonic, walletFromWIF, walletFromPriv, walletToWIF, newMnemonic,
  fetchUtxos, fetchFeeRateGrainsPerVByte, broadcastTx, fetchTxStatus,
  bytesToHex, hexToBytes, schnorr, sha256, dblSha, convertBits,
  encodeBech32m, decodeBech32m, p2trScriptPubKey, txidLE,
  partyKeyFromInput, parseXOnlyKey, addressToProgram,
  verifySchnorrSig, signForXOnly, scriptPathSigDigestEx, buildScriptPathSpend,
  keypathTxVBytes, buildKeypathTx, keypathSigDigestEx, tweakKeypath,
};

const OP = {
  FALSE: 0x00,
  DROP: 0x75,
  EQUALVERIFY: 0x88,
  SHA256: 0xa8,
  CHECKSIG: 0xac,
  CLTV: 0xb1,
};
const TAPLEAF_VERSION = 0xc0;
const EMPTY = new Uint8Array(0);
const MAX_SEQ = 0xffffffff;

export const SWAP_KIND = "pearl-swap";
export const SWAP_VERSION = 1;
export const DESCRIPTOR_PREFIX = "swap:v1";
/** Pearl block time in seconds (pearl-knowledge.md: ~194 s/block). */
export const PEARL_BLOCK_SECS = 194;
/** Bitcoin block time in seconds (protocol target). */
export const BTC_BLOCK_SECS = 600;
/** Input sequence used by the refund spend (BIP-68/112/113: < 0xffffffff
 *  opts the input into nLockTime). */
export const REFUND_SEQUENCE = 0xfffffffe;
/** T1 - T2 below this many blocks triggers a safety-margin warning. */
export const MIN_T1_T2_GAP = 144;
/** Timelocks must clear the chain tip by at least this many blocks. */
export const MIN_TIP_CLEARANCE = 6;
/** Preimage is always 32 bytes. */
export const PREIMAGE_LEN = 32;

/** Parse a decimal amount string into its smallest unit (Number, exact).
 *  Fleet-standard strict form — digits with an optional fraction of at
 *  most 8 decimal places, computed in BigInt and range-checked to a safe
 *  integer. This replaces the UI's old float parse
 *  (Math.round(Number(x) * 1e8)), which silently rounded sub-unit inputs
 *  like "0.000000015" instead of rejecting them and accepted hex/exponent
 *  forms like "0x10" (= 16 whole units) and "1e3": in a swap forge the
 *  parsed amounts are locked into the HTLC, so a misparse is a
 *  wrong-amount swap, not a display glitch. Throws on bad input. */
function parseDecimalToSmallest(s, unitName) {
  if (typeof s !== "string") throw new Error("amount must be a string");
  const t = s.trim();
  const m = /^(\d+)(?:\.(\d{1,8}))?$/.exec(t);
  if (!m) throw new Error(`invalid ${unitName} amount: ${t.slice(0, 40)}`);
  const smallest = BigInt(m[1]) * BigInt(GRAIN_PER_PRL) + (m[2] ? BigInt(m[2].padEnd(8, "0")) : 0n);
  if (smallest > BigInt(Number.MAX_SAFE_INTEGER)) {
    throw new Error(`${unitName} amount out of range: ${t.slice(0, 40)}`);
  }
  return Number(smallest);
}
/** Parse a PRL amount string into grains (exact). See above. */
export function parsePRLToGrains(s) { return parseDecimalToSmallest(s, "PRL"); }
/** Parse a BTC amount string into satoshis (exact). See above. */
export function parseBTCToSats(s) { return parseDecimalToSmallest(s, "BTC"); }

function constEq(a, b) {
  if (!(a instanceof Uint8Array) || !(b instanceof Uint8Array) || a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a[i] ^ b[i];
  return d === 0;
}

function pushData(data) {
  const b = data instanceof Uint8Array ? data : Uint8Array.from(data);
  if (b.length === 0) return [OP.FALSE];
  if (b.length <= 75) return [b.length, ...b];
  if (b.length <= 255) return [0x4c, b.length, ...b];
  throw new Error("push exceeds 255 bytes");
}

/** Minimal script-number encoding (non-negative), same as escrow-core. */
export function encodeScriptNum(n) {
  if (!Number.isSafeInteger(n) || n < 0) throw new Error("script number must be a non-negative safe integer");
  if (n === 0) return new Uint8Array([OP.FALSE]);
  const out = [];
  let v = n;
  while (v > 0) { out.push(v & 0xff); v = Math.floor(v / 256); }
  if (out[out.length - 1] & 0x80) out.push(0x00);
  return Uint8Array.from(out);
}

function checkHeight(h, name) {
  if (!Number.isSafeInteger(h) || h <= 0 || h >= 500000000) {
    throw new Error(`${name} must be a positive block height (< 500000000)`);
  }
  return h;
}

/* ------------------------------------------------------------------ */
/* Script templates                                                    */
/* ------------------------------------------------------------------ */

/** Claim leaf (Bob's): OP_SHA256 <H> OP_EQUALVERIFY <bob_xonly> OP_CHECKSIG.
 *  Anyone who knows the preimage AND holds Bob's key can claim. Witness:
 *  [bob_sig, preimage, claimScript, controlBlock]. */
export function buildClaimScript(secretHash, bobXOnly) {
  const h = secretHash instanceof Uint8Array ? secretHash : hexToBytes(String(secretHash).trim().toLowerCase());
  if (h.length !== 32) throw new Error("secret hash must be 32 bytes");
  const bob = bobXOnly instanceof Uint8Array ? bobXOnly : parseXOnlyKey(bobXOnly);
  if (bob.length !== 32) throw new Error("bob key must be 32 bytes");
  schnorr.utils.lift_x(bytesToNumberBE(bob));
  return Uint8Array.from([
    OP.SHA256, ...pushData(h),
    OP.EQUALVERIFY, ...pushData(bob),
    OP.CHECKSIG,
  ]);
}

/** Refund leaf (Alice's): <T1> OP_CHECKLOCKTIMEVERIFY OP_DROP <alice_xonly> OP_CHECKSIG.
 *  Spendable only by Alice's key once chain height >= T1, with the spending
 *  tx carrying nLockTime = T1 and input sequence 0xfffffffe. */
export function buildRefundScript(aliceXOnly, t1) {
  const alice = aliceXOnly instanceof Uint8Array ? aliceXOnly : parseXOnlyKey(aliceXOnly);
  if (alice.length !== 32) throw new Error("alice key must be 32 bytes");
  schnorr.utils.lift_x(bytesToNumberBE(alice));
  checkHeight(t1, "T1");
  return Uint8Array.from([
    ...pushData(encodeScriptNum(t1)),
    OP.CLTV, OP.DROP, ...pushData(alice),
    OP.CHECKSIG,
  ]);
}

/** NUMS internal key: H("PearlSwapNUMS/v1" || claimLeafHash || refundLeafHash)
 *  lifted to the curve (leaf order is canonical: claim first, refund second).
 *  Nobody knows the discrete log, so keypath spending is impossible — coins
 *  move only through the two HTLC leaves. Deterministic; the counter fallback
 *  exists only for the astronomically-unlikely x >= p case. */
export function numsInternalKey(claimLeafHash, refundLeafHash) {
  for (const h of [claimLeafHash, refundLeafHash]) {
    if (!(h instanceof Uint8Array) || h.length !== 32) throw new Error("leaf hash must be 32 bytes");
  }
  const base = Uint8Array.from([...claimLeafHash, ...refundLeafHash]);
  for (let c = 0; c < 256; c++) {
    const preimage = c === 0 ? base : Uint8Array.from([...base, c]);
    const h = taggedHash("PearlSwapNUMS/v1", preimage);
    try {
      schnorr.utils.lift_x(bytesToNumberBE(h));
      return h;
    } catch { /* try next counter */ }
  }
  throw new Error("NUMS lift failed (unreachable in practice)");
}

function tapBranch(a, b) {
  const [x, y] = bytesToHex(a) <= bytesToHex(b) ? [a, b] : [b, a];
  return taggedHash("TapBranch", Uint8Array.from([...x, ...y]));
}

/** Two-leaf taptree under the NUMS internal key. Returns the swap address,
 *  spk, both control blocks (65 bytes each), and everything needed to
 *  re-derive the contract from the swap spec. */
export function swapTaptree(network, claimScript, refundScript) {
  if (!(claimScript instanceof Uint8Array) || claimScript.length === 0) throw new Error("bad claim script");
  if (!(refundScript instanceof Uint8Array) || refundScript.length === 0) throw new Error("bad refund script");
  const leafHashes = [tapLeafHash(claimScript), tapLeafHash(refundScript)];
  const internalXOnly = numsInternalKey(leafHashes[0], leafHashes[1]);
  const root = tapBranch(leafHashes[0], leafHashes[1]);
  const t = taggedHash("TapTweak", Uint8Array.from([...internalXOnly, ...root]));
  const P = schnorr.utils.lift_x(bytesToNumberBE(internalXOnly));
  const Q = P.add(schnorr.Point.BASE.multiply(bytesToNumberBE(t)));
  const tweakedX = schnorr.utils.pointToBytes(Q);
  const parity = Q.toAffine().y & 1n ? 1 : 0;
  const controlBlocks = leafHashes.map((lh, i) =>
    Uint8Array.from([TAPLEAF_VERSION | parity, ...internalXOnly, ...leafHashes[1 - i]]));
  return {
    internalXOnly, leafHashes, root, tweak: t, tweakedX, parity,
    address: encodeBech32m(network.hrp, 1, tweakedX),
    spk: p2trScriptPubKey(tweakedX),
    controlBlocks, // [claim control block, refund control block]
  };
}

/** Independently re-derive the tweaked key from a control block and check it
 *  matches — the same verification a wallet does before funding. */
export function verifySwapControlBlock(internalXOnly, leafScript, controlBlock, tweakedX) {
  try {
    if (!(controlBlock instanceof Uint8Array) || controlBlock.length !== 65) return false;
    if ((controlBlock[0] & 0xfe) !== TAPLEAF_VERSION) return false;
    if (!constEq(controlBlock.slice(1, 33), internalXOnly)) return false;
    const leafHash = tapLeafHash(leafScript);
    const sibling = controlBlock.slice(33, 65);
    const root = tapBranch(leafHash, sibling);
    const t = taggedHash("TapTweak", Uint8Array.from([...internalXOnly, ...root]));
    const P = schnorr.utils.lift_x(bytesToNumberBE(internalXOnly));
    const Q = P.add(schnorr.Point.BASE.multiply(bytesToNumberBE(t)));
    const x = schnorr.utils.pointToBytes(Q);
    const parity = Q.toAffine().y & 1n ? 1 : 0;
    return constEq(x, tweakedX) && (controlBlock[0] & 0x01) === parity;
  } catch {
    return false;
  }
}

/* ------------------------------------------------------------------ */
/* Preimage / secret hash                                              */
/* ------------------------------------------------------------------ */

/** Generate a fresh 32-byte preimage (CSPRNG). The preimage IS the money:
 *  whoever reveals it can claim the PRL — generate, back up, then clear. */
export function generatePreimage() {
  const c = globalThis.crypto;
  if (!c || typeof c.getRandomValues !== "function") throw new Error("no CSPRNG available");
  const p = new Uint8Array(PREIMAGE_LEN);
  c.getRandomValues(p);
  return p;
}

/** H = SHA-256(preimage). */
export function secretHashOf(preimage) {
  const p = preimage instanceof Uint8Array ? preimage : hexToBytes(String(preimage).trim().toLowerCase());
  if (p.length !== PREIMAGE_LEN) throw new Error("preimage must be 32 bytes");
  return sha256(p);
}

export function parsePreimage(hex) {
  const t = String(hex || "").trim().toLowerCase();
  if (!/^[0-9a-f]{64}$/.test(t)) throw new Error("preimage must be 64 hex characters (32 bytes)");
  return hexToBytes(t);
}

/* ------------------------------------------------------------------ */
/* Swap spec: propose / descriptor / shareable JSON                     */
/* ------------------------------------------------------------------ */

/** x-only pubkey for a 32-byte private key (even-Y normalized, BIP-340). */
export function pubkeyFromPriv(priv) {
  const p = priv instanceof Uint8Array ? priv : hexToBytes(String(priv).trim());
  if (p.length !== 32) throw new Error("private key must be 32 bytes");
  const P = secp256k1.ProjectivePoint.fromPrivateKey(p);
  return bytesToHex(P.toRawBytes(true).slice(1));
}

/**
 * Propose a swap. One side (the role running this call) fills in the agreed
 * parameters; the other side re-derives the identical contract from the
 * shareable JSON.
 *
 * params:
 *   role: "alice" | "bob"
 *   network: NETWORKS.mainnet | NETWORKS.testnet
 *   prlGrains: PRL locked by Alice (>= dust)
 *   btcSats: BTC locked by Bob (coordination only — no BTC moves through Pearl)
 *   preimageHex: 64-hex preimage (Alice's side; required unless secretHashHex given)
 *   secretHashHex: 64-hex H (Bob's side; required unless preimageHex given)
 *   aliceKeyInput / bobKeyInput: 64-hex x-only pubkey or 12/24-word mnemonic
 *   t1, t2: Pearl block heights; T1 = Alice's PRL refund (longer), T2 = Bob's
 *     BTC refund deadline expressed as a Pearl height (shorter)
 *   feeRateGrainsPerVByte: for the lock/claim/refund fee planning
 *
 * Guards: T1 <= T2 is refused; T1 - T2 < 144 warns (returned as a warning,
 * not a refusal — the parties may still proceed knowingly).
 *
 * Returns { swap, secrets }: swap is fully serializable (safe to share);
 * secrets holds private keys IN MEMORY ONLY and never enters the JSON.
 */
export function proposeSwap(params) {
  const {
    role, network, prlGrains, btcSats, preimageHex, secretHashHex,
    aliceKeyInput, bobKeyInput, t1, t2, feeRateGrainsPerVByte,
  } = params || {};
  if (role !== "alice" && role !== "bob") throw new Error('role must be "alice" or "bob"');
  if (!network || !network.hrp) throw new Error("bad network");
  if (!Number.isSafeInteger(prlGrains) || prlGrains < DUST_GRAIN) {
    throw new Error(`PRL amount must be >= dust (${DUST_GRAIN} grains)`);
  }
  if (!Number.isSafeInteger(btcSats) || btcSats <= 0) throw new Error("BTC amount must be a positive number of sats");
  let preimage = null;
  let secretHash;
  if (preimageHex) {
    preimage = parsePreimage(preimageHex);
    secretHash = secretHashOf(preimage);
    if (secretHashHex && bytesToHex(secretHash) !== String(secretHashHex).trim().toLowerCase()) {
      throw new Error("preimage does not hash to the given secret hash");
    }
  } else if (secretHashHex) {
    const t = String(secretHashHex).trim().toLowerCase();
    if (!/^[0-9a-f]{64}$/.test(t)) throw new Error("secret hash must be 64 hex characters");
    secretHash = hexToBytes(t);
  } else {
    throw new Error("need either the preimage (Alice) or the secret hash (Bob)");
  }
  checkHeight(t1, "T1");
  checkHeight(t2, "T2");
  if (t1 <= t2) {
    throw new Error(`T1 (${t1}) must be greater than T2 (${t2}): Alice's PRL refund must expire after Bob's BTC refund deadline`);
  }
  const warnings = [];
  if (t1 - t2 < MIN_T1_T2_GAP) {
    warnings.push(`T1 - T2 = ${t1 - t2} blocks is below the ${MIN_T1_T2_GAP}-block safety margin — Alice's refund window is tight`);
  }
  if (!Number.isFinite(feeRateGrainsPerVByte) || feeRateGrainsPerVByte <= 0) throw new Error("bad fee rate");
  const alice = partyKeyFromInput(aliceKeyInput, network);
  const bob = partyKeyFromInput(bobKeyInput, network);
  const aliceXOnly = bytesToHex(alice.xonly);
  const bobXOnly = bytesToHex(bob.xonly);
  if (aliceXOnly === bobXOnly) throw new Error("Alice and Bob must use different keys");

  const claimScript = buildClaimScript(secretHash, bob.xonly);
  const refundScript = buildRefundScript(alice.xonly, t1);
  const tree = swapTaptree(network, claimScript, refundScript);
  for (const [script, cb] of [[claimScript, tree.controlBlocks[0]], [refundScript, tree.controlBlocks[1]]]) {
    if (!verifySwapControlBlock(tree.internalXOnly, script, cb, tree.tweakedX)) {
      throw new Error("internal control-block self-check failed");
    }
  }

  const secrets = [];
  if (alice.priv) secrets.push({ xonly: aliceXOnly, priv: bytesToHex(alice.priv), role: "alice" });
  if (bob.priv) secrets.push({ xonly: bobXOnly, priv: bytesToHex(bob.priv), role: "bob" });

  const swap = {
    kind: SWAP_KIND,
    version: SWAP_VERSION,
    role,
    network: network.id,
    hrp: network.hrp,
    prlGrains,
    btcSats,
    secretHashHex: bytesToHex(secretHash),
    hasPreimage: !!preimage, // preimage itself NEVER enters the spec
    t1, t2,
    aliceXOnly, bobXOnly,
    aliceKeySource: alice.source, bobKeySource: bob.source,
    feeRateGrainsPerVByte,
    claimScriptHex: bytesToHex(claimScript),
    claimAsm: swapScriptAsm(claimScript),
    refundScriptHex: bytesToHex(refundScript),
    refundAsm: swapScriptAsm(refundScript),
    internalKeyHex: bytesToHex(tree.internalXOnly),
    tweakedHex: bytesToHex(tree.tweakedX),
    claimControlBlockHex: bytesToHex(tree.controlBlocks[0]),
    refundControlBlockHex: bytesToHex(tree.controlBlocks[1]),
    address: tree.address,
    spkHex: bytesToHex(tree.spk),
    warnings,
  };
  swap.descriptor = swapDescriptor(swap);
  return { swap, secrets };
}

/** Compact, copy-pasteable descriptor:
 *  swap:v1:<hrp>:<role>:<prlGrains>:<btcSats>:<H>:<T1>:<T2> */
export function swapDescriptor(swap) {
  return `${DESCRIPTOR_PREFIX}:${swap.hrp}:${swap.role}:${swap.prlGrains}:${swap.btcSats}:${swap.secretHashHex}:${swap.t1}:${swap.t2}`;
}

/** Canonical JSON for a swap spec (what gets copied / QR-encoded / saved).
 *  Carries no preimage and no private keys — safe to share with anyone. */
export function serializeSwap(swap) {
  return JSON.stringify(swap);
}

/**
 * Parse + fully re-derive a swap spec: JSON shape, field validation, script
 * rebuild from keys+params, taptree re-derivation, control-block self-check,
 * and descriptor round-trip. Throws on anything unexpected — a tampered spec
 * can never produce a fundable address. The preimage is never required here
 * (Bob's side loads the spec without it).
 */
export function parseSwapSpec(json, network) {
  let s;
  try {
    s = typeof json === "string" ? JSON.parse(json) : json;
  } catch {
    throw new Error("swap spec is not valid JSON");
  }
  if (!s || s.kind !== SWAP_KIND || s.version !== SWAP_VERSION) {
    throw new Error("not a Pearl Swap spec (kind pearl-swap, version 1)");
  }
  if (s.hrp !== network.hrp) throw new Error(`spec is for ${s.hrp}, not ${network.hrp}`);
  const { swap } = proposeSwap({
    role: s.role,
    network,
    prlGrains: s.prlGrains,
    btcSats: s.btcSats,
    secretHashHex: s.secretHashHex,
    aliceKeyInput: s.aliceXOnly,
    bobKeyInput: s.bobXOnly,
    t1: s.t1,
    t2: s.t2,
    feeRateGrainsPerVByte: s.feeRateGrainsPerVByte,
  });
  // Every re-derived field must match byte-for-byte — tampering anywhere
  // (amounts, heights, hash, keys, role) changes the contract or descriptor.
  for (const f of ["address", "spkHex", "claimScriptHex", "refundScriptHex",
    "internalKeyHex", "tweakedHex", "claimControlBlockHex", "refundControlBlockHex",
    "aliceXOnly", "bobXOnly", "secretHashHex", "descriptor"]) {
    if (swap[f] !== s[f]) throw new Error(`swap spec failed re-derivation check on ${f} — the spec was tampered with`);
  }
  if (swap.prlGrains !== s.prlGrains || swap.btcSats !== s.btcSats ||
      swap.t1 !== s.t1 || swap.t2 !== s.t2 || swap.role !== s.role) {
    throw new Error("swap spec failed re-derivation check — the spec was tampered with");
  }
  // Return a normalized copy so downstream code never trusts raw input.
  return { ...swap, warnings: Array.isArray(s.warnings) ? s.warnings.map(String) : [] };
}

/** Parse a compact descriptor back into its fields (no keys — the descriptor
 *  alone cannot re-derive the contract; pair it with the JSON spec). */
export function parseDescriptor(descriptor) {
  const t = String(descriptor || "").trim();
  const parts = t.split(":");
  // swap:v1:<hrp>:<role>:<prlGrains>:<btcSats>:<H>:<T1>:<T2>  →  9 parts
  if (parts.length !== 9 || parts[0] !== "swap" || parts[1] !== "v1") {
    throw new Error("bad swap descriptor (expected swap:v1:<hrp>:<role>:<prlGrains>:<btcSats>:<H>:<T1>:<T2>)");
  }
  const prlGrains = Number(parts[4]);
  const btcSats = Number(parts[5]);
  const t1 = Number(parts[7]);
  const t2 = Number(parts[8]);
  if (!Number.isSafeInteger(prlGrains) || !Number.isSafeInteger(btcSats) ||
      !Number.isSafeInteger(t1) || !Number.isSafeInteger(t2)) {
    throw new Error("bad swap descriptor: amounts/heights are not integers");
  }
  if (!/^[0-9a-f]{64}$/i.test(parts[6] || "")) throw new Error("bad swap descriptor: secret hash");
  return {
    hrp: parts[2],
    role: parts[3],
    prlGrains,
    btcSats,
    secretHashHex: parts[6].toLowerCase(),
    t1,
    t2,
  };
}

/** Human summary of a swap spec for the UI. */
export function describeSwap(swap) {
  const who = swap.role === "alice" ? "Alice (PRL side, initiator)" : "Bob (BTC side)";
  return {
    role: who,
    address: swap.address,
    prl: (swap.prlGrains / GRAIN_PER_PRL).toFixed(8),
    btc: (swap.btcSats / 1e8).toFixed(8) + " BTC",
    secretHash: swap.secretHashHex,
    t1: swap.t1, t2: swap.t2,
    gap: swap.t1 - swap.t2,
    alice: swap.aliceXOnly.slice(0, 16) + "…",
    bob: swap.bobXOnly.slice(0, 16) + "…",
    descriptor: swap.descriptor,
    warnings: swap.warnings || [],
  };
}

/* ------------------------------------------------------------------ */
/* Script disassembly                                                  */
/* ------------------------------------------------------------------ */

/** Human-readable disassembly of the HTLC scripts (contract review screen). */
export function swapScriptAsm(script) {
  const names = {
    0x75: "OP_DROP", 0x87: "OP_EQUAL", 0x88: "OP_EQUALVERIFY",
    0xa8: "OP_SHA256", 0xac: "OP_CHECKSIG", 0xb1: "OP_CHECKLOCKTIMEVERIFY",
  };
  const parts = [];
  let i = 0;
  while (i < script.length) {
    const op = script[i];
    if (op === 0x00) { parts.push("0"); i++; continue; }
    if (op >= 0x51 && op <= 0x60) { parts.push(String(op - 0x50)); i++; continue; }
    if (op <= 0x4b || op === 0x4c) {
      let len, hlen;
      if (op <= 0x4b) { len = op; hlen = 1; }
      else { len = script[i + 1]; hlen = 2; }
      const data = script.slice(i + hlen, i + hlen + len);
      if (len <= 5) {
        // small script number (e.g. a timelock height) — decode it
        let v = 0;
        for (let k = data.length - 1; k >= 0; k--) v = v * 256 + data[k];
        parts.push(`<${v}>`);
      } else {
        parts.push(`<${bytesToHex(data).slice(0, 12)}…${data.length}B>`);
      }
      i += hlen + len;
      continue;
    }
    parts.push(names[op] || `0x${op.toString(16).padStart(2, "0")}`);
    i++;
  }
  return parts.join(" ");
}

/* ------------------------------------------------------------------ */
/* Lock: Alice funds the swap address (keypath spend from her wallet)  */
/* ------------------------------------------------------------------ */

/** Accept a funder key as 64-hex private key, WIF, or 12/24-word mnemonic
 *  (BIP-86 account key, same scheme as Pearl Sign). Returns { priv, internalXOnly, address }. */
export function funderKeyFromInput(input, network) {
  const t = String(input || "").trim();
  if (/^[0-9a-fA-F]{64}$/.test(t)) return walletFromPriv(hexToBytes(t.toLowerCase()), network);
  if (/^[1-9A-HJ-NP-Za-km-z]{30,60}$/.test(t)) {
    try { return walletFromWIF(t, network); } catch { /* fall through to mnemonic/error */ }
  }
  const words = t.split(/\s+/);
  if (words.length === 12 || words.length === 24) return walletFromMnemonic(t, network);
  throw new Error("funder key must be a 32-byte hex private key, WIF, or a 12/24-word mnemonic");
}

/** The funder's P2TR scriptPubKey (keypath, empty script tree). */
export function funderSpkHex(internalXOnly) {
  const { tweakedX } = tweakKeypath(internalXOnly);
  return bytesToHex(p2trScriptPubKey(tweakedX));
}

/**
 * Build Alice's funding transaction: keypath spend(s) from her wallet paying
 * prlGrains to the swap address, change back to her, exact fee math.
 *
 * utxos: [{ txid, vout, value, spkHex? }] — when spkHex is present it MUST
 *   equal the funder's scriptPubKey (belong-check); when absent the UTXO is
 *   accepted with a returned warning (the page cannot verify belonging offline).
 *
 * Every input signature is re-verified against its BIP-341 keypath digest
 * before the hex is returned — a bad signature never reaches the caller.
 */
export function buildLockTx(network, {
  funderPriv, funderInternalXOnly, utxos, swapProgram, prlGrains, feeRateGrainsPerVByte,
}) {
  const priv = funderPriv instanceof Uint8Array ? funderPriv : hexToBytes(String(funderPriv).trim().toLowerCase());
  if (priv.length !== 32) throw new Error("funder private key must be 32 bytes");
  const internalXOnly = funderInternalXOnly instanceof Uint8Array
    ? funderInternalXOnly : hexToBytes(String(funderInternalXOnly).trim().toLowerCase());
  // The privkey must actually control the internal key (even-Y normalized).
  const derived = pubkeyFromPriv(priv);
  if (derived !== bytesToHex(internalXOnly)) {
    throw new Error("funder private key does not match the funder public key");
  }
  if (!(swapProgram instanceof Uint8Array) || swapProgram.length !== 32) {
    throw new Error("swap program must be 32 bytes");
  }
  if (!Number.isSafeInteger(prlGrains) || prlGrains < DUST_GRAIN) {
    throw new Error(`lock amount below dust (${DUST_GRAIN} grains)`);
  }
  if (!Number.isFinite(feeRateGrainsPerVByte) || feeRateGrainsPerVByte <= 0) throw new Error("bad fee rate");
  if (!Array.isArray(utxos) || utxos.length === 0) throw new Error("need at least one funder UTXO");
  const funderSpk = p2trScriptPubKey(tweakKeypath(internalXOnly).tweakedX);
  const funderSpkHex = bytesToHex(funderSpk);
  const warnings = [];
  let totalIn = 0;
  const inputs = utxos.map((u, i) => {
    if (!/^[0-9a-f]{64}$/i.test(u?.txid || "")) throw new Error(`utxo ${i}: bad txid`);
    if (!Number.isInteger(u?.vout) || u.vout < 0) throw new Error(`utxo ${i}: bad vout`);
    if (!Number.isSafeInteger(u?.value) || u.value <= 0) throw new Error(`utxo ${i}: bad value`);
    if (u.spkHex) {
      if (String(u.spkHex).trim().toLowerCase() !== funderSpkHex) {
        throw new Error(`utxo ${i}: scriptPubKey does not belong to the funder address — refusing`);
      }
    } else {
      warnings.push(`utxo ${i}: belonging not verifiable offline — confirm it belongs to the funder address`);
    }
    totalIn += u.value;
    return { txid: u.txid.toLowerCase(), vout: u.vout, value: u.value, priv, internalXOnly };
  });

  const changeProgram = tweakKeypath(internalXOnly).tweakedX;
  // Try with change first; fold dust change into the fee otherwise.
  let nOut = 2;
  let fee = Math.ceil(keypathTxVBytes(inputs.length, nOut) * feeRateGrainsPerVByte);
  let change = totalIn - prlGrains - fee;
  let outputs;
  if (change >= DUST_GRAIN) {
    outputs = [
      { program: swapProgram, value: prlGrains },
      { program: changeProgram, value: change },
    ];
  } else {
    nOut = 1;
    fee = Math.ceil(keypathTxVBytes(inputs.length, nOut) * feeRateGrainsPerVByte);
    change = totalIn - prlGrains - fee;
    if (change < 0) throw new Error(`insufficient funds: need ${prlGrains + fee} grains, have ${totalIn}`);
    if (change > 0) { fee += change; change = 0; }
    outputs = [{ program: swapProgram, value: prlGrains }];
  }
  if (change < 0) throw new Error(`insufficient funds: need ${prlGrains + fee} grains, have ${totalIn}`);

  const built = buildKeypathTx(network, inputs, outputs);
  // Per-signature re-verification: parse the witness sigs back out of the
  // built tx and check each against its BIP-341 keypath digest.
  const parsed = parseTx(built.hex);
  const { tweakedX } = tweakKeypath(internalXOnly);
  const digestInputs = inputs.map((inp) => ({ txid: inp.txid, vout: inp.vout, value: inp.value, spk: funderSpk }));
  parsed.inputs.forEach((pin, i) => {
    if (pin.witness.length !== 1 || pin.witness[0].length !== 64) {
      throw new Error(`lock tx: input ${i} witness is not a single 64-byte signature`);
    }
    const digest = keypathSigDigestEx(network, digestInputs, outputs, MAX_SEQ, i, 0x00);
    if (!verifySchnorrSig(pin.witness[0], digest, tweakedX)) {
      throw new Error(`lock tx: input ${i} signature failed re-verification — refusing to expose the hex`);
    }
  });
  return {
    txid: built.txid, hex: built.hex,
    feeGrains: fee, vBytes: keypathTxVBytes(inputs.length, nOut),
    changeGrains: change, warnings,
  };
}

/* ------------------------------------------------------------------ */
/* Claim: Bob spends via the claim leaf, revealing the preimage        */
/* ------------------------------------------------------------------ */

/** Exact worst-case vBytes for a claim spend (1 P2TR output). */
export function claimSpendVBytes(swap) {
  return spendVBytes({
    nOut: 1,
    scriptLen: swap.claimScriptHex.length / 2,
    controlLen: 65,
    stackLens: [64, PREIMAGE_LEN], // bob_sig + preimage
  });
}

/**
 * Build Bob's claim spend: script-path spend of the claim leaf.
 * Guards: preimage must hash to H (wrong preimage refused); the signing key
 * must be Bob's key from the spec; the signature is re-verified before the
 * witness is assembled. The preimage is revealed in the witness — Alice
 * extracts it from the confirmed claim tx to claim the BTC side.
 */
export function buildClaimSpend(network, swap, {
  utxo, preimageHex, bobPrivHex, destAddress, feeRateGrainsPerVByte,
}) {
  const preimage = parsePreimage(preimageHex);
  if (bytesToHex(secretHashOf(preimage)) !== swap.secretHashHex) {
    throw new Error("preimage does not hash to the swap's secret hash — claim refused");
  }
  const bobXOnly = pubkeyFromPriv(bobPrivHex);
  if (bobXOnly !== swap.bobXOnly) {
    throw new Error("this key is not Bob's claim key for this swap — claim refused");
  }
  if (!/^[0-9a-f]{64}$/i.test(utxo?.txid || "")) throw new Error("bad utxo txid");
  if (!Number.isInteger(utxo?.vout) || utxo.vout < 0) throw new Error("bad utxo vout");
  if (!Number.isSafeInteger(utxo?.value) || utxo.value <= 0) throw new Error("bad utxo value");
  if (!Number.isFinite(feeRateGrainsPerVByte) || feeRateGrainsPerVByte <= 0) throw new Error("bad fee rate");
  const destProgram = addressToProgram(destAddress, network);
  const fee = Math.ceil(claimSpendVBytes(swap) * feeRateGrainsPerVByte);
  const value = utxo.value - fee;
  if (value < DUST_GRAIN) {
    throw new Error(`claim output ${value} grains is below dust after fees — UTXO too small`);
  }
  const claimScript = hexToBytes(swap.claimScriptHex);
  const controlBlock = hexToBytes(swap.claimControlBlockHex);
  const input = { txid: utxo.txid.toLowerCase(), vout: utxo.vout, value: utxo.value, spk: hexToBytes(swap.spkHex) };
  const outputs = [{ program: destProgram, value }];
  const digest = scriptPathSigDigestEx(network, input, outputs, claimScript, {});
  const sig = signForXOnly(hexToBytes(String(bobPrivHex).trim().toLowerCase()), digest);
  if (!verifySchnorrSig(sig, digest, hexToBytes(swap.bobXOnly))) {
    throw new Error("claim signature failed re-verification — refusing to build the tx");
  }
  const spend = buildScriptPathSpend(
    network, input, outputs, claimScript, controlBlock, [sig, preimage], {},
  );
  if (spend.digest !== bytesToHex(digest)) throw new Error("internal: claim digest mismatch");
  return { ...spend, feeGrains: fee, preimageHex: bytesToHex(preimage) };
}

/* ------------------------------------------------------------------ */
/* Refund: Alice reclaims after T1 via the refund leaf                 */
/* ------------------------------------------------------------------ */

/** Exact worst-case vBytes for a refund spend (1 P2TR output). */
export function refundSpendVBytes(swap) {
  return spendVBytes({
    nOut: 1,
    scriptLen: swap.refundScriptHex.length / 2,
    controlLen: 65,
    stackLens: [64], // alice_sig
  });
}

/**
 * Build Alice's refund spend: script-path spend of the refund leaf.
 * Guards: currentHeight >= T1 (refuse before maturity with a clear message);
 * the signing key must be Alice's key; nLockTime = T1 and input sequence =
 * 0xfffffffe are hard-coded (a 0xffffffff sequence can never be produced —
 * the function takes no sequence parameter).
 */
export function buildRefundSpend(network, swap, {
  utxo, alicePrivHex, destAddress, feeRateGrainsPerVByte, currentHeight,
}) {
  if (!Number.isSafeInteger(currentHeight) || currentHeight < 0) throw new Error("bad current height");
  if (currentHeight < swap.t1) {
    throw new Error(`refund not yet mature: chain height ${currentHeight} < T1 ${swap.t1} (${swap.t1 - currentHeight} blocks to go)`);
  }
  const aliceXOnly = pubkeyFromPriv(alicePrivHex);
  if (aliceXOnly !== swap.aliceXOnly) {
    throw new Error("this key is not Alice's refund key for this swap — refund refused");
  }
  if (!/^[0-9a-f]{64}$/i.test(utxo?.txid || "")) throw new Error("bad utxo txid");
  if (!Number.isInteger(utxo?.vout) || utxo.vout < 0) throw new Error("bad utxo vout");
  if (!Number.isSafeInteger(utxo?.value) || utxo.value <= 0) throw new Error("bad utxo value");
  if (!Number.isFinite(feeRateGrainsPerVByte) || feeRateGrainsPerVByte <= 0) throw new Error("bad fee rate");
  const destProgram = addressToProgram(destAddress, network);
  const fee = Math.ceil(refundSpendVBytes(swap) * feeRateGrainsPerVByte);
  const value = utxo.value - fee;
  if (value < DUST_GRAIN) {
    throw new Error(`refund output ${value} grains is below dust after fees — UTXO too small`);
  }
  const refundScript = hexToBytes(swap.refundScriptHex);
  const controlBlock = hexToBytes(swap.refundControlBlockHex);
  const input = { txid: utxo.txid.toLowerCase(), vout: utxo.vout, value: utxo.value, spk: hexToBytes(swap.spkHex) };
  const outputs = [{ program: destProgram, value }];
  const digest = scriptPathSigDigestEx(
    network, input, outputs, refundScript,
    { sequence: REFUND_SEQUENCE, locktime: swap.t1 },
  );
  const sig = signForXOnly(hexToBytes(String(alicePrivHex).trim().toLowerCase()), digest);
  if (!verifySchnorrSig(sig, digest, hexToBytes(swap.aliceXOnly))) {
    throw new Error("refund signature failed re-verification — refusing to build the tx");
  }
  const spend = buildScriptPathSpend(
    network, input, outputs, refundScript, controlBlock, [sig],
    { sequence: REFUND_SEQUENCE, locktime: swap.t1 },
  );
  if (spend.digest !== bytesToHex(digest)) throw new Error("internal: refund digest mismatch");
  // Structural check on the wire bytes: nLockTime == T1, sequence == 0xfffffffe.
  const parsed = parseTx(spend.hex);
  if (parsed.locktime !== swap.t1) throw new Error("internal: refund locktime != T1");
  if (parsed.inputs[0].sequence !== REFUND_SEQUENCE) throw new Error("internal: refund sequence != 0xfffffffe");
  return { ...spend, feeGrains: fee };
}

/* ------------------------------------------------------------------ */
/* Segwit tx parser + preimage extraction                              */
/* ------------------------------------------------------------------ */

/** Parse a raw (segwit or legacy) transaction. Returns
 *  { version, inputs: [{txid, vout, sequence, scriptSig, witness[]}],
 *    outputs: [{value, spk}], locktime }. txid is big-endian hex. */
export function parseTx(txHex) {
  const raw = hexToBytes(String(txHex).trim().toLowerCase());
  if (raw.length < 10) throw new Error("tx too short");
  let o = 0;
  const read = (n) => {
    if (o + n > raw.length) throw new Error("tx truncated");
    const s = raw.slice(o, o + n);
    o += n;
    return s;
  };
  const readU32 = () => {
    const b = read(4);
    return (b[0] | (b[1] << 8) | (b[2] << 16) | (b[3] << 24)) >>> 0;
  };
  const readU64 = () => {
    const b = read(8);
    let v = 0n;
    for (let i = 7; i >= 0; i--) v = (v << 8n) | BigInt(b[i]);
    if (v > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error("value out of range");
    return Number(v);
  };
  const readVarint = () => {
    const f = read(1)[0];
    if (f < 0xfd) return f;
    if (f === 0xfd) { const b = read(2); return b[0] | (b[1] << 8); }
    if (f === 0xfe) return readU32();
    throw new Error("64-bit varint unsupported");
  };
  const version = readU32();
  let segwit = false;
  if (raw[o] === 0x00 && raw[o + 1] === 0x01) { segwit = true; o += 2; }
  const nIn = readVarint();
  if (nIn === 0) throw new Error("tx has no inputs");
  const inputs = [];
  for (let i = 0; i < nIn; i++) {
    const prev = read(32);
    const txid = bytesToHex(Uint8Array.from(prev).reverse());
    const vout = readU32();
    const slen = readVarint();
    const scriptSig = read(slen);
    const sequence = readU32();
    inputs.push({ txid, vout, sequence, scriptSig, witness: [] });
  }
  const nOut = readVarint();
  const outputs = [];
  for (let i = 0; i < nOut; i++) {
    const value = readU64();
    const slen = readVarint();
    const spk = read(slen);
    outputs.push({ value, spk });
  }
  if (segwit) {
    for (const inp of inputs) {
      const n = readVarint();
      for (let i = 0; i < n; i++) {
        const l = readVarint();
        inp.witness.push(read(l));
      }
    }
  }
  const locktime = readU32();
  if (o !== raw.length) throw new Error("tx has trailing bytes");
  return { version, inputs, outputs, locktime, segwit };
}

/**
 * Extract the preimage from Bob's on-chain claim transaction: scan every
 * input witness for a 32-byte item whose SHA-256 equals the swap's secret
 * hash. Throws when no such item exists (e.g. a refund tx, or an unrelated tx).
 */
export function extractPreimage(claimTxHex, secretHashHex) {
  const H = String(secretHashHex).trim().toLowerCase();
  if (!/^[0-9a-f]{64}$/.test(H)) throw new Error("bad secret hash");
  const tx = parseTx(claimTxHex);
  for (const inp of tx.inputs) {
    for (const item of inp.witness) {
      if (item.length === PREIMAGE_LEN && bytesToHex(sha256(item)) === H) {
        return bytesToHex(item);
      }
    }
  }
  throw new Error("no preimage revealed in this transaction's witnesses — is this Bob's claim tx?");
}

/* ------------------------------------------------------------------ */
/* Swap state classification (Track step)                              */
/* ------------------------------------------------------------------ */

/**
 * Classify the swap's on-chain state from observed transactions.
 *   fundingSeen: the lock tx is confirmed (or seen)
 *   spends: [{ txid, hex }] — transactions spending the swap UTXO
 * Returns { state, txid?, preimageHex? } where state is one of:
 *   "awaiting-funding" | "locked" | "claimed" | "refunded" | "spent-unknown"
 */
export function classifySwapState(swap, { fundingSeen, spends }) {
  const list = Array.isArray(spends) ? spends : [];
  for (const s of list) {
    let tx;
    try { tx = parseTx(s.hex); } catch { continue; }
    // A claim reveals the preimage in the witness.
    let preimage = null;
    for (const inp of tx.inputs) {
      for (const item of inp.witness) {
        if (item.length === PREIMAGE_LEN && bytesToHex(sha256(item)) === swap.secretHashHex) {
          preimage = bytesToHex(item);
        }
      }
    }
    if (preimage) return { state: "claimed", txid: s.txid, preimageHex: preimage };
    if (tx.locktime >= swap.t1) return { state: "refunded", txid: s.txid };
    return { state: "spent-unknown", txid: s.txid };
  }
  return { state: fundingSeen ? "locked" : "awaiting-funding" };
}

/** Countdown to the timelocks from a chain tip. */
export function swapCountdown(swap, tipHeight) {
  const toGo = (h) => Math.max(0, h - tipHeight);
  return {
    tipHeight,
    blocksToT1: toGo(swap.t1),
    blocksToT2: toGo(swap.t2),
    etaSecsToT1: toGo(swap.t1) * PEARL_BLOCK_SECS,
    etaSecsToT2: toGo(swap.t2) * PEARL_BLOCK_SECS,
    t1Mature: tipHeight >= swap.t1,
    t2Reached: tipHeight >= swap.t2,
  };
}

/* ------------------------------------------------------------------ */
/* Bitcoin mirror template (Bob's side — built by HIS tooling)         */
/* ------------------------------------------------------------------ */

/**
 * Generate the exact Bitcoin-side mirror contract template. The page does
 * NOT build Bitcoin transactions — Bob (or his Bitcoin wallet/tooling)
 * assembles the BTC HTLC from this template:
 *   claim leaf:  OP_SHA256 <H> OP_EQUALVERIFY <bob_xonly> OP_CHECKSIG   (identical bytes)
 *   refund leaf: <T2_btc> OP_CHECKLOCKTIMEVERIFY OP_DROP <bob_xonly> OP_CHECKSIG
 * under the same NUMS derivation, addressed as bc1p…/tb1p… (bech32m).
 *
 * opts: { btcNetwork: "mainnet"|"testnet", btcTip?, pearlTip? } — when both
 * tips are given, a suggested Bitcoin refund height is computed from T2;
 * otherwise the template shows the conversion formula with a worked example.
 */
export function btcMirrorTemplate(swap, opts = {}) {
  const btcNetwork = opts.btcNetwork === "testnet" ? "testnet" : "mainnet";
  const hrp = btcNetwork === "mainnet" ? "bc" : "tb";
  const secretHash = hexToBytes(swap.secretHashHex);
  const bobXOnly = hexToBytes(swap.bobXOnly);
  const claimScript = buildClaimScript(secretHash, bobXOnly);

  let t2Btc = null;
  let conversionNote;
  if (Number.isSafeInteger(opts.btcTip) && Number.isSafeInteger(opts.pearlTip)) {
    const pearlSecsToT2 = Math.max(0, swap.t2 - opts.pearlTip) * PEARL_BLOCK_SECS;
    const btcBlocks = Math.ceil(pearlSecsToT2 / BTC_BLOCK_SECS);
    t2Btc = opts.btcTip + btcBlocks + MIN_TIP_CLEARANCE;
    conversionNote =
      `T2 (Pearl height ${swap.t2}) is ~${Math.round(pearlSecsToT2 / 3600)}h after Pearl tip ${opts.pearlTip}; ` +
      `+${btcBlocks} Bitcoin blocks from tip ${opts.btcTip}, plus ${MIN_TIP_CLEARANCE} safety blocks → ` +
      `suggested Bitcoin refund height ${t2Btc}. Recompute from live tips before funding.`;
  } else {
    conversionNote =
      `No chain tips supplied, so no Bitcoin height is suggested. Convert T2 yourself: ` +
      `btcHeight = btcTip + ceil(((T2 - pearlTip) * ${PEARL_BLOCK_SECS}) / ${BTC_BLOCK_SECS}) + ${MIN_TIP_CLEARANCE}. ` +
      `Example: Pearl tip 120000, T2 ${swap.t2} → ${(swap.t2 - 120000) * PEARL_BLOCK_SECS / 3600 >= 0 ? "~" + Math.round((swap.t2 - 120000) * PEARL_BLOCK_SECS / 3600) + "h" : "in the past"}; ` +
      `at Bitcoin tip 870000 that is height ${870000 + Math.ceil(Math.max(0, (swap.t2 - 120000)) * PEARL_BLOCK_SECS / BTC_BLOCK_SECS) + MIN_TIP_CLEARANCE}.`;
  }
  const refundScript = t2Btc === null
    ? null
    : buildRefundScript(bobXOnly, t2Btc); // Bob's key refunds the BTC side

  // The BTC contract is its own taptree (same NUMS tag, BTC leaves) — only
  // the address HRP differs from Pearl; the tweaked key is chain-independent.
  let address = null, tweakedHex = null, internalKeyHex = null,
    controlBlocksHex = null, refundScriptHex = null, refundAsm = null;
  if (refundScript) {
    const tree = swapTaptree({ hrp }, claimScript, refundScript);
    address = tree.address;
    tweakedHex = bytesToHex(tree.tweakedX);
    internalKeyHex = bytesToHex(tree.internalXOnly);
    controlBlocksHex = tree.controlBlocks.map(bytesToHex);
    refundScriptHex = bytesToHex(refundScript);
    refundAsm = swapScriptAsm(refundScript);
    for (const [script, cb] of [[claimScript, tree.controlBlocks[0]], [refundScript, tree.controlBlocks[1]]]) {
      if (!verifySwapControlBlock(tree.internalXOnly, script, cb, tree.tweakedX)) {
        throw new Error("internal BTC mirror control-block self-check failed");
      }
    }
  }

  const steps = [
    `1. Confirm the secret hash H = ${swap.secretHashHex} matches what Alice published (SHA-256 of her preimage).`,
    `2. Reproduce the HTLC scripts below with your own Bitcoin tooling — the claim leaf is byte-identical on both chains.`,
    `3. Derive the ${hrp === "bc" ? "mainnet bc1p" : "testnet tb1p"} address from the scripts (NUMS internal key H("PearlSwapNUMS/v1" || claimLeafHash || refundLeafHash), BIP-341 taptree, bech32m). The page computed ${address || "(address needs live chain tips — see conversion note)"} — verify it independently before funding.`,
    `4. Fund the BTC address with exactly ${swap.btcSats} sats (${(swap.btcSats / 1e8).toFixed(8)} BTC) and wait for confirmations.`,
    `5. Verify Alice's PRL lock is confirmed at the Pearl swap address ${swap.address} before considering the swap live.`,
    `6. To claim the PRL: sign a Pearl script-path spend of the claim leaf revealing the preimage (Bob's key + preimage witness). Your claim tx reveals the preimage on Pearl — Alice then uses it to claim the BTC.`,
    `7. If Alice never locks (or you abort): after Bitcoin height ${t2Btc === null ? "(compute from live chain tips first)" : t2Btc} (your refund timeout), refund the BTC with nLockTime = that height and input sequence 0xfffffffe.`,
    `8. NEVER reuse a preimage across swaps. Clear secrets after the swap settles.`,
  ];
  return {
    btcNetwork, hrp,
    claimScriptHex: bytesToHex(claimScript),
    claimAsm: swapScriptAsm(claimScript),
    refundScriptHex, refundAsm,
    suggestedBtcRefundHeight: t2Btc,
    conversionNote,
    address, tweakedHex, internalKeyHex, controlBlocksHex,
    steps,
    honestNote: "Pearl Swap does not build or sign Bitcoin transactions. The BTC HTLC above must be assembled, funded, and spent with the counterparty's own Bitcoin wallet or tooling — this template gives the exact scripts and parameters so any implementation reproduces the same address.",
  };
}
